### ISSUE TITLE
[Feature] Compat with Mythic Metals and More Gems

### ISSUE THREAD

**Issue by Sunconure11** [SuperMartijn642/OreGrowth#1]
Just as the title says. Compat with these mods would be done by having ore clusters that grow from their ores.

**Comment by Sunconure11** [comment]
Also, maybe make a mega issue for mods that could get compat like this?

**Comment by SuperMartijn642** [comment]
Ore Growth 1.0.4 now has recipes for both Mythic Metals and More Gems [FABRIC]. Thank you for the suggestion!

> Also, maybe make a mega issue for mods that could get compat like this?

I don't really see the point in that. People can just create an issue requesting integration for a certain mod and I will close it whenever I add it.
