### ISSUE TITLE
missing textures on custom growth ores

### ISSUE THREAD

**Issue by knoxhack** [SuperMartijn642/OreGrowth#11]
Some of the textures are missing for some reason when adding some custom ores

**Comment by knoxhack** [comment]
example:

[gravel_growth.json](https://github.com/SuperMartijn642/OreGrowth/files/13730285/gravel_growth.json)

**Comment by knoxhack** [comment]
only happens with the blocks from Compressium: 
[https://www.curseforge.com/minecraft/mc-mods/compressium](https://www.curseforge.com/minecraft/mc-mods/compressium)

**Comment by knoxhack** [comment]
![2023-12-20_12 18 45](https://github.com/SuperMartijn642/OreGrowth/assets/9358725/8586540d-6dca-45de-8007-37ec3330dbd2)

**Comment by knoxhack** [comment]
![2023-12-20_12 23 27](https://github.com/SuperMartijn642/OreGrowth/assets/9358725/5d9a634e-3c3b-4309-a132-22481af48691)

**Comment by SuperMartijn642** [comment]
There's a template for a reason, please provide the info requested in the template. I have no idea what version of Minecraft or what version of the mod you are using.

**Comment by knoxhack** [comment]
- Minecraft, 
1.20.1

- Ore Growth,
- oregrowth-1.0.11-forge-mc1.20.1

**What mod loader are you using?**: Fabric/Forge/NeoForge/Quilt
Forge 47.2.1

**Comment by knoxhack** [comment]
It can be replicated on Fantasy Skies-1.1.9: 
[https://www.curseforge.com/minecraft/modpacks/fantasy-skies/files/4971657](https://www.curseforge.com/minecraft/modpacks/fantasy-skies/files/4971657)

**Comment by SuperMartijn642** [comment]
Seems to be working fine.
![image](https://github.com/SuperMartijn642/OreGrowth/assets/12382965/73bd6cef-8cbf-41a0-8b2c-7b308d126a09)
