### ISSUE TITLE
Compressed Block crystals break VERY SLOWLY Version

### ISSUE THREAD

**Issue by knoxhack** [SuperMartijn642/OreGrowth#12]
**Version Info**

- Minecraft, ...
- 1.20.1

- Ore Growth, ...
oregrowth-1.0.11-forge-mc1.20.1

**What mod loader are you using?**: Fabric/Forge/NeoForge/Quilt
Forge.47.2.1

**Description of the Bug**
[Astrobirder](https://github.com/Astrobirder) commented [5 days ago](https://github.com/NFINIT-Labs/Fantasy-Skies/issues/1#issue-2045301715) • 
Not sure if this is by design, but it seems compressed dirt and sand should be easier to break than diamonds ;-). I tried iron pick and iron shovel, with similar times. Version 1.1.7.

Link to initial issue:
[https://github.com/NFINIT-Labs/Fantasy-Skies/issues/1](https://github.com/NFINIT-Labs/Fantasy-Skies/issues/1)

**Comment by SuperMartijn642** [comment]
The crystals break at the same speed and with the same tools as the base blocks. It seems the blocks from Compressium just don't break faster with tools. Specifically, 1x compressed dirt block and 1x compressed sand block break incredibly slow with both an iron pickaxe and iron shovel.
Correctly, the crystals break at the same speed.
