### ISSUE TITLE
[Feature]This block should not be rotated

### ISSUE THREAD

**Issue by Aaki-Sakura** [SuperMartijn642/OreGrowth#13]
I don't know how to explain it, so I used this image
![GIF](https://github.com/SuperMartijn642/OreGrowth/assets/151650896/207d3142-7309-49a4-b3c0-3ae1d9165f68)

**Comment by SuperMartijn642** [comment]
That seems like a problem with whatever you are using to rotate the block. Both, vanilla nor Ore Growth allow you to rotate the crystal block. If some other mod forces it to be rotated, there's nothing I can do about that 🤷‍♂️

Also, how is this a feature request? Please use the appropriate template, so I have the info I need. I have no clue what version of Minecraft, what version of Ore Growth, or what modloader you are using.
