### ISSUE TITLE
[Bug] [Sodium Incompatibility] All ore growths use iron ore texture when running Sodium

### ISSUE THREAD

**Issue by BinaryElement** [SuperMartijn642/OreGrowth#14]
**Version Info**
- Minecraft, 1.20.4
- Ore Growth, 1.0.11

**What mod loader are you using?**: Fabric

**Description of the Bug**
When running with Sodium (graphical optimization mod: https://github.com/CaffeineMC/sodium-fabric) all ore crystals will use the same texture, specifically that from iron ore.

Wasn't sure if I should mark this as a bug or feature request.

**Steps to Reproduce**
Install Sodium
Install Ore Growth
Create new world
Observe ore crystals

**Screenshots**
Ores and their growths:
![image](https://github.com/SuperMartijn642/OreGrowth/assets/33382750/dea6afb7-a2ad-4eee-b95e-7edec1aeefa5)

Complete list of mods (only Sodium, Ore Growth, and their dependencies)
![image](https://github.com/SuperMartijn642/OreGrowth/assets/33382750/c05e2d79-72c9-4212-bd12-ad10400b6c6c)

**Comment by SuperMartijn642** [comment]
You will have to install Indium. Sodium breaks any mod using the Fabric rendering API. Nothing I can do about that

**Comment by BinaryElement** [comment]
Ah fantastic, I didn't know about this.  Indium does indeed fix the issue.  Issue is a non-issue then!  I think it might be a good idea to point this out in the compatibility section on Modrinth

**Comment by aplro** [comment]
I was about to make another bug report on this but decided to look at closed cases I think you should mention it somewhere since it's pretty frequently used mod.
