### ISSUE TITLE
Apatite crystals not growing from Thermal Foundation [Bug] ...

### ISSUE THREAD

**Issue by ToastyCoral** [SuperMartijn642/OreGrowth#15]
**Version Info**
- Minecraft 1.20.1
- Ore Growth, 1.0.11

**What mod loader are you using? Forge

Apatite crystals don't grow from apatite ore or deepslate apatite ore. I've had one in my world for 10 hours within render distance and there's been no progress.
...

**Steps to Reproduce**
Place apatite ore down
Increase tick speed

**Comment by SuperMartijn642** [comment]
The recipes for Thermal Foundation were based on the 1.19.2 version, hence all the ores added in 1.20.1 were absent.
I have now added recipes for the missing ores, apatite, sapphire, and ruby, in version 1.0.11a of Ore Growth.
Thank you for reporting the issue!
