### ISSUE TITLE
Designated Configuration File for "unofficial recipies"

### ISSUE THREAD

**Issue by minefreak022** [SuperMartijn642/OreGrowth#17]
Yeah, as it stands im either stupid or the only way to add ores not natively supported, e.g. alltheores, is to directly modify the jar file, making it a tedious task to use in multiplayer. introducing a "config" file could prove a "easy" way to modify existing ore recipies, as well as easing support  for non native ores.

im inexperienced with modding and coding. if this request is unfeasible please let me know. 
secondly, i am aware that this is a problem of luxury, so i expect nothing to come of it

**Comment by SuperMartijn642** [comment]
Ore growth recipes are just handled using regular recipe files, just like vanilla crafting recipes. You can thus add or change recipes using a datapack, just like you'd for vanilla recipes.

**Comment by minefreak022** [comment]
ouf. in that case just me being stupid. but there is nothing in the documentation that tells me how to do that. there is just that vague line of placing files in the "recipes folder". again im not well versed in modding/coding/datapack design, so im sorry for wasting time.
