### ISSUE TITLE
[Feature] REI Support

### ISSUE THREAD

**Issue by Bentcheesee** [SuperMartijn642/OreGrowth#18]
Since this already has support for JEI, would it be possible to also have support for REI?

**Comment by SuperMartijn642** [comment]
I thought Roughly Enough Items was able to load plugins for Just Enough Items, however this appears to only be the case on Forge.
I have now added integration with Roughly Enough Items in version 1.1.0 of Ore Growth, so it will show the ore growth recipes similar to how they are shown in JEI.
Thank you for the suggestion!
