### ISSUE TITLE
Only iron ore textures used for the ore clusters

### ISSUE THREAD

**Issue by TommyC81** [SuperMartijn642/OreGrowth#19]
**Version Info**
- Minecraft 1.20.4
- Ore Growth 1.0.11 (oregrowth-1.0.11-fabric-mc1.20.4.jar)
- Using Faithful 32x resource pack (if it matters, but no difference observed in switching it on or off).

**What mod loader are you using?**: Fabric loader 0.15.7 (fabric-api-0.96.4+1.20.4.jar)

**Description of the Bug**
Only iron ore texture used for the ore clusters. Looks odd on coal, copper etc.

**Steps to Reproduce**
Install Ore Growth, observe iron ore textures on all ore crystals.

Expected that coal texture would be used for crystals on coal etc.

**Screenshots**
![image](https://github.com/SuperMartijn642/OreGrowth/assets/1904092/658e4e2b-2b1f-4548-bd4b-cd7e2891d702)

**Comment by SuperMartijn642** [comment]
Sodium breaks Fabric rendering API, thus any mod using Fabric rendering API won't work. You can install Indium which patches Sodium to support Fabric API.

**Comment by TommyC81** [comment]
I'm away from computer at the moment, but I guess this could be a tricky case of various rendering plug-ins interacting.

I have, as far as I'm aware, the latest versions of Indium, Sodium, Sodium-Extra, and Nvidium in use. Also ETF and EM etc. Basically everything that is in the Breakneck 3.4.4 mod pack, as well as some additional mods. I can provide exact details later if you believe it is useful.

**Comment by TommyC81** [comment]
I'm away from computer at the moment, but I guess this could be a tricky case of various rendering plug-ins interacting.

I have, as far as I'm aware, the latest versions of Indium, Sodium, Sodium-Extra, and Nvidium in use. Also ETF and EMF etc. Basically everything that is in the Breakneck 3.4.4 mod pack, as well as some additional mods. I can provide exact details later if you believe it is useful.

**Comment by SuperMartijn642** [comment]
Ah sorry, most of the time it is people using Sodium without Indium. Hence, I just assumed that was the case here.

Still it's likely some interaction with another mod as it works fine with just Ore Growth installed. Could you narrow down which other mod is needed to reproduce the issue?

**Comment by TommyC81** [comment]
No worries at all, I'll see what I can do to locate the error. Hopefully something easy/obvious.

In the meanwhile, these are the exact versions I'm currently using of various mods:
- sodium-fabric-0.5.8+mc1.20.4
- sodium-extra-0.5.4+mc1.20.4-build.116
- indium-1.0.30+mc1.20.4
- nvidium-0.2.6-beta
- entity_model_features_fabric_1.20.4-1.3
- entity_texture_features_fabric_1.20.4-5.2.3

**Comment by TommyC81** [comment]
Removing nvidium-0.2.6-beta had no effect on texture (only reduced FPS markedly...).

**Comment by TommyC81** [comment]
I've tried some simpler things that were within reach. No conclusion on what is causing the wrong texture.

**Comment by SuperMartijn642** [comment]
Easiest is to use binary search. Just disable half the mods (besides Ore Growth ofc) at a time. Then, if the issue goes away, continue with the half you removed. If the issue persists, continue with the half still enabled.
Just repeat until you find the mod which causes it. Even for large number of mods, binary search shouldn't take very many attempts.
