### ISSUE TITLE
[1.19.2-] Random tick mixin checks recipe on every call

### ISSUE THREAD

**Issue by embeddedt** [SuperMartijn642/OreGrowth#21]
When backporting from 1.20.1 to 1.19.2, it appears the injector that enables random ticking on ore blocks was moved into [`isRandomlyTicking`](https://github.com/SuperMartijn642/OreGrowth/blob/809e0dd8436adf0a5c0aa23e36529a22c04db63e/src/main/java/com/supermartijn642/oregrowth/mixin/BlockStateBaseMixin.java#L22-L32) rather than `initCache`. In a server profile, I noted that this is 1% of the total tick time, which seems like a lot for such a simple feature.

![image](https://github.com/SuperMartijn642/OreGrowth/assets/42941056/9b63a965-fd3d-491c-8559-9ea00ca117cc)

Possibly this could be cached manually on older versions? One approach could be to inject into `initCache` and store a flag if the block has an ore growth recipe, and then have `isRandomlyTicking` return `true` if that flag is set. Checking the flag should be much faster than looking up the recipe.

**Comment by SuperMartijn642** [comment]
Whoops, I do vaguely remember it being an issue that there was no `isRandomlyTicking` flag I could change when porting to 1.19.2, but I guess I just mixed into `isRandomlyTicking` and forgot about it 😅
It checking for a recipe every time a block is random ticked is definitely not ideal.

I have now changed it so it checks once in `initCache` and then caches the value like you suggested.
Thank you for looking into and reporting the issue, I really appreciate all these improvements you submit for my mods! 🙂
