### ISSUE TITLE
[Feature] Apply Fortune on the Ore Growth

### ISSUE THREAD

**Issue by yunjang** [SuperMartijn642/OreGrowth#22]
**Is your feature request related to a problem? Please describe.**
It seems when players mine the growth on the ores, Fortune does not apply to the mined growth. From a balance perspective, this is understandable.

**Describe the solution you'd like**
If possible, would we be able to get a configuration added that is defaulted to false for applying Fortune? This way, users can opt in or out from benefitting from Fortune.

Thank you very much for your time and consideration.

**Comment by SuperMartijn642** [comment]
> ... Fortune does not apply to the mined growth. From a balance perspective, this is understandable.

Indeed, as the mod is already rather 'overpowered', making the crystals drop more with fortune would make that even worse.
I have changed the format for ore growth recipes now in version 1.1.0 of Ore Growth. Crystals may now have multiple drops, different drops per growth stages, and drops may come from loot tables. This makes adding a simple toggle to apply fortune not that simple 😅

With the addition of drops from loot tables, you can technically do this yourself by overwriting the recipes to obtain drops from a loot table which then applies fortune. However, if you want to obtain more resources, I would suggest simply increasing the global growth speed multiplier in the config file for Ore Growth.
Still, thank you for the suggestion!
