### ISSUE TITLE
[Feature] Add tag support for ore blocks

### ISSUE THREAD

**Issue by LlubNek** [SuperMartijn642/OreGrowth#24]
**Is your feature request related to a problem? Please describe.**
Right now, I need to add each individual ore block for each mod, even when many of these ore blocks should behave the same way.  For example, Excavated Variants ores each need to be manually added for each ore and stone type.  With tags, this could just work, without any additional work from the mod pack creator.

**Describe the solution you'd like**
Instead of
```
{
   "type": "oregrowth:ore_growth",
   "base": "minecraft:copper_ore", // block the crystal grows on
   "stages": 4, // number of growth stages the crystal has
   "spawn_chance": 0.2, // chance for a crystal to spawn when the
                        // base receives a random tick
   "growth_chance": 0.3, // chance for a crystal to grow when it
                         // receives a random tick
   "result": { // item dropped when a fully grown crystal is broken
      "item": "minecraft:raw_copper",
      "count": 1
   }
}
```
use
```
{
   "type": "oregrowth:ore_growth",
   "base": "#minecraft:copper_ores", // block the crystal grows on, # indicates tag
   "stages": 4, // number of growth stages the crystal has
   "spawn_chance": 0.2, // chance for a crystal to spawn when the
                        // base receives a random tick
   "growth_chance": 0.3, // chance for a crystal to grow when it
                         // receives a random tick
   "result": { // item dropped when a fully grown crystal is broken
      "item": "#forge:raw_materials/copper", // # indicates tag, pick first matching item
      "count": 1
   }
}
```

**Comment by SuperMartijn642** [comment]
I have changed the recipe format for ore growth recipes so the 'base' key can either be a string or an array of strings. Each entry may then be a block or a block tag.
Having a tag for the result doesn't make much sense to me as it will have to drop a specific item. This is the same for vanilla recipes where inputs can be any ingredient, be it an item, a set of items, or a tag, but the output has to be a specific item.

The updated format is available in version 1.1.0 of Ore Growth and I've updated the example on CurseForge and Modrinth.
Thank you for the suggestion!
