### ISSUE TITLE
[Feature] ...AE2 Support

### ISSUE THREAD

**Issue by Mysticpasta1** [SuperMartijn642/OreGrowth#26]
using the growth accelerators to growth them faster and having compact for placing and destroying ores with formation and annihilation planes respectively along with support for growth on ae2 ores

**Comment by SuperMartijn642** [comment]
> using the growth accelerators to growth them faster

I have added the ore crystal block to the tag for the growth accelerators from AE2, so the growth accelerators should speed them up now in version 1.1.0.

>  having compact for placing and destroying ores with formation and annihilation planes

I am not sure what you mean by this. You can already destroy the crystals using annihilation planes just like any other block. As you can't obtain the crystals in survival, the formation plane is not really applicable, although if the item is cheated in it can be placed using annihilation planes.

> along with support for growth on ae2 ores

Applied Energistics 2 doesn't add any ores 🤔

**Comment by Mysticpasta1** [comment]
it adds a certus quartz ore

**Comment by Mysticpasta1** [comment]
as for everything else good job :D

**Comment by SuperMartijn642** [comment]
> it adds a certus quartz ore

Certus quartz is obtained from meteorites similar to amethyst geodes.
