### ISSUE TITLE
[Bug] Ore growth not droping.

### ISSUE THREAD

**Issue by adex345** [SuperMartijn642/OreGrowth#28]
**Version Info**
- Minecraft, 1.21
- Ore Growth, v1.1.1+a

**What mod loader are you using?**: Fabric

**Description of the Bug**
Nothing drops after five or six drops. confirmed 100% growth with jade. After server restart cycle continues. It might just be mod incompatibility but i dont know with one.

**Steps to Reproduce**
install client and run server server of https://modrinth.com/modpack/quallityvanillatweaked modpack and mine 5 ore growth

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
This should be fixed in version 1.1.2 of Ore Growth released earlier today.

**Comment by adex345** [comment]
Thank you for reply!
