### ISSUE TITLE
[Feature] Primary chance and secondary output

### ISSUE THREAD

**Issue by MrEizy** [SuperMartijn642/OreGrowth#3]
**Is your feature request related to a problem? Please describe.**
Not a problem itself, would just be neat to have!

**Describe the solution you'd like**
Would love for us to be able to have secondary output and add a chance option to primary and secondary outputs!

**Comment by SuperMartijn642** [comment]
I have updated the format for ore growth recipes and a recipe can now have multiple drops, a chance of obtaining a certain drop, and drops for specific growth stages.
The updated format is available in version 1.1.0 of Ore Growth and I have updated the example on CurseForge and Modrinth accordingly.
Thank you for the suggestion!
