### ISSUE TITLE
Add mekanism compat 1.21.1 minecraft

### ISSUE THREAD

**Issue by DatrixTheHybridShadowWolf** [SuperMartijn642/OreGrowth#30]
**Is your feature request related to a problem? Please describe.**
I'm wanting to have mekanism compat added to this mod as I like this mod

**Describe the solution you'd like**
Add crystal growth to Mekanism ores.

**Comment by SuperMartijn642** [comment]
Ore Growth already has recipes for Mekanism ores. Any specific ores for which it is not working?

**Comment by DatrixTheHybridShadowWolf** [comment]
Lead, TIn, Osmium I believe...If it's already in there, then it should have shown some growth of the crystals on them... Perhaps I was thinking of another mod altogether and that mod was on the brain. I'll check on this and get back with you and see if it works and I just didn't pay attention to it.

**Comment by SuperMartijn642** [comment]
Yeah those should already have recipes. You can check JEI/REI to see if there's ore growth recipes for a specific block. Could be that the recipes are there, but something else is broken causing them to not grow perhaps.

**Comment by DatrixTheHybridShadowWolf** [comment]
I checked in on EMI/JEI/REI, but it doesn't show the growth recipes for the respective ores such as Tin, Osmium, Uranium, Fluorite and Lead. Would that mean that some other mod is breaking that functionality with the recipies?

**Comment by SuperMartijn642** [comment]
I will have a look, could just be that the registry names of some blocks/items in Mekanism changed since I added the recipes. I usually update before Mekanism does, so it might just be that it changed since the previous Minecraft version.

What modloader, what Minecraft version, and what version of Ore Growth are you using?

**Comment by DatrixTheHybridShadowWolf** [comment]
Oh I see.

NeoForge 21.1.72 
Minecraft 1.21.1
Ore Growth 1.1.2

**Comment by SuperMartijn642** [comment]
Yup, it seems Mekanism changed their naming for nugget items from `makanism:x_nugget` to `mekanism:nugget_x`.
It should be fixed now in version 1.1.2a. Might take a couple minutes for the file to get approved on CurseForge.

**Comment by DatrixTheHybridShadowWolf** [comment]
Thanks for the response and the fix. I appreciate this.

**Comment by DatrixTheHybridShadowWolf** [comment]
I took a look at the recipes for Ore Growth 1.1.2a and it now shows the recipe for them. Thanks again
