### ISSUE TITLE
[Bug] When mined always shows iron particles, no matter the ore crystal

### ISSUE THREAD

**Issue by KarmasuL** [SuperMartijn642/OreGrowth#33]
**Version Info**
- Minecraft, 1.21.3
- Ore Growth, 1.1.2 fabric

**What mod loader are you using?**: Fabric (with curseforge

**Description of the Bug**
When i mine an ore crystal the particles fall are always iron ore particles. 
When i mine the ore itself it shows the correct particles.
See also [comment](https://github.com/SuperMartijn642/OreGrowth/issues/9#issuecomment-2441558281)

**Steps to Reproduce**
To test it I just loaded the game up with only those things active in curseforge and created a new world:
Ore growth
Fabric API
SuperMartijn642's Config Lib (1.1.8)
SuperMartijn642's core Lib (1.1.17a)

Tested it on coal and copper in this new world.

**Screenshots**
![2024-11-04_23 18 00](https://github.com/user-attachments/assets/0d7f887b-7cf3-4cf7-a818-4780dd97db9a)

**Comment by SuperMartijn642** [comment]
Should be fixed now in version 1.1.3 of Ore Growth.
Thank you for reporting the issue!

**Comment by KarmasuL** [comment]
Looks good on my end.
