### ISSUE TITLE
Ores become an iron ore sprite instead of a regular ore sprite

### ISSUE THREAD

**Issue by GoldenDove20** [SuperMartijn642/OreGrowth#4]
1.20.2
Minecraft 1.20.2
Ore Growth 1.20.2

Fabric

All of the ores are assigned a Iron Ore Growth Sprite when growing

When any of the Ore grows, it causes it always to be a Iron Sprite

https://imgur.com/gallery/iFc2wb2 new to github so not sure how screenshots work here so here is a link to it in imgur instead

The problem is 100% one of my mods fault since it works fine normally but I cannot find out which one is causing it 

Here are all of my current mods in alphabetical order:

3dskinlayers
additionallanterns
animal feeding trough
appleskin
architectury 
balm fabric
betterstats
betterthirdperson
boat item view
buildguide
chunkloader
collective
connectedglass
ctov
do a barrel roll
entityculling
explorerscompass
fabric api
fabric kotlin
fallingtree
fast hopper
formations
formationnether
formationoverworld
from the fog
fusion fabric
globalxp
glore
immersive portals
itemcollectors
jade
jamlib
jei
journeymap
kleeslabs
lambdynamiclights
libIPN
mavapi
mavm
minerally (I originally thought this was the cause since they are similar but it wasn't)
modernfix
naturecompass
netherportalfix
notenoughanimations
nullscape
oregrowth
plushies
puffish skills
rechiseled
right click harvest
scarecrowterritory
sodium fabric
spawnermod
stackrefill
structory towers
SuperMartijin642 configlib
SuperMartijin642 corelib
tectonic
terrablender
truedarkness
verdantvibes
villagernames
wardentools
wirelesschargers
wso16

**Comment by SuperMartijn642** [comment]
Ah if you are using Sodium, you will also have to install [Indium](https://www.curseforge.com/minecraft/mc-mods/indium). 
Sodium replaces the vanilla renderer with one which ignores the Fabric Rendering API. Indium patches Sodium to support the Fabric Rendering API.

Not entirely sure if that's the only reason here. Could you try it with Indium installed as well? (or without Sodium)

**Comment by GoldenDove20** [comment]
Oh Cool!  installing Indium fixed the problem https://imgur.com/gallery/xedGQnw

I thought I had something conflicting, thank you very much!
