### ISSUE TITLE
[Bug] All growths appear as the iron ore texture

### ISSUE THREAD

**Issue by UpsideDom** [SuperMartijn642/OreGrowth#6]
**Version Info**
- Minecraft, 1.20.2
- Ore Growth, 1.0.5

**What mod loader are you using?**: Fabric

**Description of the Bug**
No matter which block the growth is appearing on, it uses the iron ore texture.

**Steps to Reproduce**
Unsure, using multiple mods and resource packs.

**Screenshots**

![2023-10-21_19 35 22](https://github.com/SuperMartijn642/OreGrowth/assets/148659973/e48b35cf-f5fb-432d-add6-71c863d76124)

**Comment by SuperMartijn642** [comment]
Are you using Sodium and if so, do you have Indium installed?
