### ISSUE TITLE
[Feature] Support for Industrial Revolution Mod

### ISSUE THREAD

**Issue by NolanHewitt** [SuperMartijn642/OreGrowth#7]
This mod: https://www.curseforge.com/minecraft/mc-mods/industrial-revolution

Just a simple request to add built-in support for this mod, if not no worries, should be possible to add support manually.

**Comment by SuperMartijn642** [comment]
What kind of support do you want? As far as I can tell Industrial Revolution doesn't add any ores.

**Comment by NolanHewitt** [comment]
It adds Tin, Silver, Lead, and Tungsten ore.

**Comment by SuperMartijn642** [comment]
In what Minecraft version/modloader/mod version is that?
In the latest version for Fabric 1.20.1, it does not add any new ores.

**Comment by NolanHewitt** [comment]
It’s for fabric 1.20.1, it adds those 4 ores plus a new dust. It has many other types of ingots, but those are all craftable and don’t have ores.

**Comment by SuperMartijn642** [comment]
Are you sure? I tried it yesterday, even double checked, but it didn't add any new ores.

**Comment by NolanHewitt** [comment]
Yeah, most of the stuff in that mod is made with the new ores and ingots. The MK2 circuit for example uses silver.

**Comment by SuperMartijn642** [comment]
I can indeed see silver plates in the recipe for the MK2 circuit, but there appears to be no way to obtain them (or at least JEI doesn't show any). There are also no silver ingots or ores.
![image](https://github.com/SuperMartijn642/OreGrowth/assets/12382965/772c248d-939a-4817-9925-93440852d55a)

**Comment by NolanHewitt** [comment]
Silver plates are made by putting silver ingots into a compressor machine, or by using the hammer. Silver ingots are gotten by smelting raw silver ore. That’s odd that you can’t see the actual ore. I use REI, maybe JEI has issues with this particular mod?

**Comment by SuperMartijn642** [comment]
Ah thanks for the hint, indeed REI shows all the items including the ores.

It seems a lot of the items from Industrial Revolution aren't in any creative tabs nor in the creative search menu. JEI usually only shows items which are available in the creative tabs which is likely why I couldn't find them in JEI either.

**Comment by SuperMartijn642** [comment]
I added ore growth recipes for the ores from Industrial Revolution now in Ore Growth version 1.0.8.
Thank you for the suggestion and thank you for me helping figure things out!

**Comment by NolanHewitt** [comment]
Thank you!!
