### ISSUE TITLE
[compatibility] with spelunkery 

### ISSUE THREAD

**Issue by jojofenin99** [SuperMartijn642/OreGrowth#8]
**Is your feature request related to a problem? Please describe.**
The problem is it does not give the rough version of material like rough diamond, and rough lapis instead it just gives the refined materials like diamonds and lapis
**Describe the solution you'd like**
I think a solution would be making it when spelunkery is installed changed the materials you get to the rough versions.

**Comment by SuperMartijn642** [comment]
I am not familiar with Spelunkery. Does it change vanilla ore drops to rough versions of the normal drops?

**Comment by SOLDIER-First** [comment]
Yes. Spelunkery makes Diamond and Emerald Ore drop rough versions of themselves that must be polished at a grindstone before you can use them. Lapis Lazuli/Redstone Ore instead drop Rough Lazurite/Rough Cinnabar, which are separate materials, and they produce Lapis/Redstone as a byproduct of being polished.

You can see a more detailed explanation at Spelunkery's wiki page [here](https://github.com/AstralOrdana/Spelunkery/wiki/Resources#rough-gemstones).

**Comment by SuperMartijn642** [comment]
Whoops forgot to close the issue here. I added recipes for when Spelunkery is installed yesterday in version 1.0.7.
Thank you both for the suggestion!
